#!/bin/sh

export AUTO=NON
export CHRONON=100
export HAUTEUR=30
export LARGEUR=30
export NB_PROIE=1
export NB_REQUINS=15
export CYCLE_REPRODUCTION_REQUIN=26
export CYCLE_REPRODUCTION_PROIE=26
export VISIBILITE_REQUIN=15
export VISIBILITE_PROIE=2
export VUE_ARRIERE_REQUIN=OUI
export VUE_ARRIERE_PROIE=OUI
export POINTS_DE_VIE_REQUIN=25
export POINTS_PAR_REPAS=6

./lancement_scenario.sh